language: android

install:
  # Check install section: http://docs.travis-ci.com/user/build-configuration/#install
  # If you'd like to skip the install stage entirely, set it to true and nothing will be run.
  - true

script:
  # By default Travis-ci executes './gradlew build connectedCheck' if no 'script:' section found.
  - ./gradlew check

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support

before_install:
 - chmod +x gradlew

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/