language: android
android:
  components:
    - build-tools-23.0.1
    - extra-android-support
    - android-23
    - sys-img-armeabi-v7a-android-23

before_install:
 - chmod +x gradlew

jdk:
  - oraclejdk8
